[package]
name = "hatecli"
version = "0.1.0"
authors = ["No3cho <79093085+No3cho@users.noreply.github.com>"]
edition = "2018"

[dependencies]
url = "2.2.1"
structopt = { version = "0.3.21", default-features = false }